name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - run: go build -o twrapper ./cmd/twrapper
        env:
          CGO_ENABLED: 0
      - run: go test -v ./...
  release:
    name: release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - uses: go-semantic-release/action@v1.11.2
        with:
          github-token: ${{ secrets.PA_TOKEN }}
